### ISSUE TITLE
Brainstorming for lyrics dataset

### ISSUE THREAD

**Issue by sachinravi14** [AI-ON/Few-Shot-Music-Generation#1]
Details of the requirements for the dataset can be found in the proposal. We are looking for suggestions for creating this dataset, including:
* Possible sources for the raw data.
* How it can be collected.
* The format of the collected dataset.

**Comment by AnishShah** [comment]
Hi, I just went through the papers in reading list. Regarding lyrics dataset, I was wondering that we can crawl lyrics from some website maybe.

**Comment by MohMehKo** [comment]
Hi, I am working on lyrics generation for a while, I am gathering lyrics data from web and add them to github https://github.com/MohMehKo/lyrics/tree/master/artist_songs
let me know if it is a good starting point.

**Comment by heaven00** [comment]
In this project https://github.com/rasbt/musicmood by Sebastian Raschka. 

The data collection is done by getting songs from [million song dataset](https://labrosa.ee.columbia.edu/millionsong/pages/getting-dataset) and then lyrics are scraped from lyricWikia  more details [here](https://github.com/rasbt/musicmood#dataset-summary) and demonstration [here](https://github.com/rasbt/musicmood/blob/master/code/collect_data/data_collection.ipynb)

**Comment by Vakuma** [comment]
Second @heaven00's idea. We will need to convert the track to MIDI format.

**Comment by sagelywizard** [comment]
Looks like the Lakh MIDI dataset has lyrics attached to ~23800 MIDI files, which might be useful. I haven't looked at the quality of the dataset yet though.

**Comment by sachinravi14** [comment]
@MohMehKo, the repository you linked to looks great! Can you give details about how the dataset was created?
1. How were the artists picked and where was the data scraped from?
2. What are the details about the dataset: specifically how many different artists are there and how many songs are there per artist on average?

**Comment by vishalbhalla** [comment]
These lyrics data sources could also be used as a good starting point.

1. [Lyrics for 57650 songs](https://www.kaggle.com/mousehead/songlyrics/data) acquired from LyricsFreak through scraping.
2. [380,000+ lyrics from MetroLyrics](https://www.kaggle.com/gyani95/380000-lyrics-from-metrolyrics)
This one also has the [source code](https://github.com/SJasoria/lyrics_substance) which explains how it was extracted from the website.
3. Moreover, the [musiXmatch ](https://labrosa.ee.columbia.edu/millionsong/musixmatch)dataset is an official lyrics collection of the Million Song Dataset (MSD). However, they use bag-of-words and not the original lyrics as the latter is protected by copyright and they do not have permissions to redistribute it.
4. A smaller dataset comprising of Year-End Hot 100 songs [50 Years of Pop Music Lyrics](https://github.com/walkerkq/musiclyrics) that Billboard has published from 1958.
